version: '3.8'

services:
  app:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=domaindb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d domaindb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: